version: "3"

services:
  db:
    image: postgres:14
    container_name: postgres_container
    ports:
      - 5436:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
volumes:
  db-store:
