name: Node.js CI

on:
  push:
    branches: [master]
    paths:
      - 'server/**'
  pull_request:
    branches: [master]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: passw0rd
        ports:
          - 5436:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        working-directory: ./server
      - name: Run tests
        run: npm test
        working-directory: ./server
        env:
          DATABASE_URL: postgres://postgres:passw0rd@localhost:5436/your_test_db
